spring.application.name=PoC
# ========== MariaDB ==========
spring.datasource.url=jdbc:mariadb://localhost:3306/quan_ly_luong
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# ========== JWT ==========
security.jwt.secret=${SECURITY_JWT_SECRET:my-very-secure-and-long-secret-key!391926}
security.jwt.expiration-millis=${SECURITY_JWT_EXPIRATION_MILLIS:7200000}

# ========== Redis ==========
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms
spring.data.redis.repositories.enabled=false
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.max-wait=2000ms
security.jwt.blacklist.prefix=${SECURITY_JWT_BLACKLIST_PREFIX:blacklist:token:}
