apiVersion: v1
kind: Secret
metadata:
  name: poc-app-secret
  namespace: default
type: Opaque
stringData:
  # Sensitive values only
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "123456"
  MARIADB_ROOT_PASSWORD: "123456"

  # JWT
  SECURITY_JWT_SECRET: "my-very-secure-and-long-secret-key!391926"
